export const influencers = [
  {
    id: 1,
    name: "Alex Johnson",
    handle: "@alexjcreates",
    avatar: "/placeholder.svg?height=100&width=100",
    category: "Lifestyle",
    followers: "1.2M",
    engagement: "4.5%",
    rating: 4.8,
    platforms: ["instagram", "youtube"],
    price: "$1,200",
    verified: true,
    trending: true,
    location: "Los Angeles, CA",
    bio: "Lifestyle content creator specializing in travel, fashion, and wellness.",
  },
  {
    id: 2,
    name: "Sophia Chen",
    handle: "@sophiaeats",
    avatar: "/placeholder.svg?height=100&width=100",
    category: "Food",
    followers: "850K",
    engagement: "5.2%",
    rating: 4.9,
    platforms: ["instagram", "twitter"],
    price: "$950",
    verified: true,
    location: "New York, NY",
    bio: "Food blogger and recipe developer with a passion for global cuisines.",
  },
  {
    id: 3,
    name: "Marcus Williams",
    handle: "@marcustech",
    avatar: "/placeholder.svg?height=100&width=100",
    category: "Technology",
    followers: "2.5M",
    engagement: "3.8%",
    rating: 4.7,
    platforms: ["youtube", "twitter"],
    price: "$2,500",
    verified: true,
    trending: true,
    location: "San Francisco, CA",
    bio: "Tech reviewer and digital lifestyle expert covering the latest gadgets and innovations.",
  },
  {
    id: 4,
    name: "Priya Sharma",
    handle: "@priyabeauty",
    avatar: "/placeholder.svg?height=100&width=100",
    category: "Beauty",
    followers: "1.8M",
    engagement: "6.1%",
    rating: 4.9,
    platforms: ["instagram", "youtube"],
    price: "$1,800",
    verified: true,
    location: "Miami, FL",
    bio: "Makeup artist and beauty educator sharing tutorials and product reviews.",
  },
  {
    id: 5,
    name: "Jordan Taylor",
    handle: "@jordanfitness",
    avatar: "/placeholder.svg?height=100&width=100",
    category: "Fitness",
    followers: "950K",
    engagement: "5.5%",
    rating: 4.6,
    platforms: ["instagram", "twitter"],
    price: "$1,100",
    location: "Chicago, IL",
    bio: "Personal trainer and fitness coach helping people achieve their health goals.",
  },
  {
    id: 6,
    name: "Emma Rodriguez",
    handle: "@emmatravels",
    avatar: "/placeholder.svg?height=100&width=100",
    category: "Travel",
    followers: "1.5M",
    engagement: "4.2%",
    rating: 4.8,
    platforms: ["instagram", "youtube"],
    price: "$1,600",
    verified: true,
    location: "Austin, TX",
    bio: "Travel blogger exploring hidden gems and sharing travel tips from around the world.",
  },
  {
    id: 7,
    name: "David Kim",
    handle: "@davidgaming",
    avatar: "/placeholder.svg?height=100&width=100",
    category: "Gaming",
    followers: "3.2M",
    engagement: "4.7%",
    rating: 4.5,
    platforms: ["youtube", "twitter"],
    price: "$2,800",
    trending: true,
    location: "Seattle, WA",
    bio: "Gaming content creator and streamer specializing in strategy and RPG games.",
  },
  {
    id: 8,
    name: "Olivia Martinez",
    handle: "@oliviafashion",
    avatar: "/placeholder.svg?height=100&width=100",
    category: "Fashion",
    followers: "1.1M",
    engagement: "5.8%",
    rating: 4.7,
    platforms: ["instagram", "twitter"],
    price: "$1,400",
    verified: true,
    location: "Paris, France",
    bio: "Fashion stylist and trend forecaster sharing outfit inspiration and style tips.",
  },
  {
    id: 9,
    name: "Tyler Brooks",
    handle: "@tylerfinance",
    avatar: "/placeholder.svg?height=100&width=100",
    category: "Finance",
    followers: "780K",
    engagement: "3.9%",
    rating: 4.8,
    platforms: ["youtube", "twitter"],
    price: "$1,900",
    new: true,
    location: "Toronto, Canada",
    bio: "Financial educator making complex money concepts simple and accessible.",
  },
  {
    id: 10,
    name: "Zoe Wilson",
    handle: "@zoeartist",
    avatar: "/placeholder.svg?height=100&width=100",
    category: "Art",
    followers: "920K",
    engagement: "6.3%",
    rating: 4.9,
    platforms: ["instagram", "youtube"],
    price: "$1,300",
    new: true,
    location: "Berlin, Germany",
    bio: "Digital artist and illustrator sharing creative processes and art tutorials.",
  },
]

